server:
  port: 8082
  servlet:
    context-path: /static/index.html
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/glxt?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
    level:
      com.example.demo.dao: debug

